"""Contract interaction utilities for the off‑chain agent.
This module uses ``web3`` (installed in the project via ``pip``) to build
lightweight contract objects from ABI JSON files that are shipped with the
contracts repository.  It never embeds secret values; the private key is
provided at runtime via the environment.
"""
import json
import os
from pathlib import Path
from typing import Any

from web3 import Web3
try:
    from web3.middleware import geth_poa_middleware
except ImportError:
    # no-op middleware for environments without geth_poa_middleware
    def geth_poa_middleware(make_request, w3):
        return make_request


# Helper to load an ABI from the contracts/build folder (generated by forge)
def _load_abi(name: str) -> Any:
    abi_path = Path(__file__).parents[1] / "contracts" / "out" / name / f"{name}.sol" / f"{name}.json"
    if not abi_path.is_file():
        raise FileNotFoundError(f"ABI file not found for contract {name}: {abi_path}")
    with abi_path.open() as f:
        data = json.load(f)
    return data["abi"]

class BaseContract:
    def __init__(self, address: str, abi_name: str, w3: Web3):
        self.address = address
        try:
            # Attempt checksum conversion; if it fails, keep raw address (useful for placeholders in mock mode)
            self.address = Web3.to_checksum_address(address)
        except Exception:
            self.address = address
        self.w3 = w3
        self.abi = _load_abi(abi_name)
        self.contract = w3.eth.contract(address=self.address, abi=self.abi)

class AgentExecutionGate(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "AgentExecutionGate", w3)

    def can_execute(self, req: dict) -> bool:
        # ``canExecute`` returns (bool, string)
        result = self.contract.functions.canExecute(req).call()
        return result[0]

    def execute(self, req: dict, private_key: str) -> str:
        """Send a transaction to ``execute`` and return the tx hash.
        The caller is responsible for signing with the provided private key.
        """
        acct = self.w3.eth.account.from_key(private_key)
        nonce = self.w3.eth.get_transaction_count(acct.address)
        tx = self.contract.functions.execute(req).build_transaction({
            "from": acct.address,
            "nonce": nonce,
            "gas": 500_000,
            "gasPrice": self.w3.toWei("5", "gwei"),
        })
        signed = acct.sign_transaction(tx)
        tx_hash = self.w3.eth.send_raw_transaction(signed.rawTransaction)
        return tx_hash.hex()

class RWAStateOracle(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "RWAStateOracle", w3)

    def is_eligible(self, asset: str, action: int) -> bool:
        return self.contract.functions.isEligible(asset, action).call()

    def get_state(self, asset: str) -> dict:
        # Returns a tuple (nav, navUpdatedAt, maxNavAge, redemptionOpen, liquidityTier)
        return self.contract.functions.assets(asset).call()

class TBillVault(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "TBillVault", w3)

    # No direct execution – kept for completeness (e.g., reading yield)
    def get_yield(self) -> int:
        # Placeholder – actual yield logic is contract‑specific.
        return self.contract.functions.getCurrentYield().call()
