"""Contract interaction utilities for the off-chain T-BillFlow agent.

Uses web3.py to build lightweight contract objects from ABI JSON files
generated by `forge build`. Never embeds secret values; the private key is
provided at runtime via environment variables.
"""

import json
from pathlib import Path
from typing import Any, Optional

from web3 import Web3

# Attempt to import PoA middleware; no-op if unavailable (web3.py v7+)
try:
    from web3.middleware import geth_poa_middleware as _poa_mw
    HAS_POA_MW = True
except ImportError:
    HAS_POA_MW = False


# ─────────────────────────────────────────────────────────────────────────────
# ABI loader
# ─────────────────────────────────────────────────────────────────────────────

def _load_abi(name: str) -> Any:
    """Load a compiled ABI from the Foundry output directory."""
    candidates = [
        Path(__file__).parents[1] / "contracts" / "out" / f"{name}.sol" / f"{name}.json",
        Path(__file__).parents[1] / "contracts" / "out" / name / f"{name}.sol" / f"{name}.json",
    ]
    for abi_path in candidates:
        if abi_path.is_file():
            with abi_path.open(encoding="utf-8") as f:
                data = json.load(f)
            return data["abi"]
    raise FileNotFoundError(
        f"ABI file not found for contract '{name}'. Tried: {[str(c) for c in candidates]}. "
        "Run 'forge build' inside the contracts/ directory first."
    )


# ─────────────────────────────────────────────────────────────────────────────
# Base contract wrapper
# ─────────────────────────────────────────────────────────────────────────────

class BaseContract:
    def __init__(self, address: str, abi_name: str, w3: Web3):
        try:
            self.address = Web3.to_checksum_address(address)
        except Exception:
            # Allow raw/placeholder addresses in mock mode
            self.address = address
        self.w3 = w3
        self.abi = _load_abi(abi_name)
        self.contract = w3.eth.contract(address=self.address, abi=self.abi)


# ─────────────────────────────────────────────────────────────────────────────
# Contract wrappers
# ─────────────────────────────────────────────────────────────────────────────

class AgentExecutionGate(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "AgentExecutionGate", w3)

    def can_execute(self, req: dict) -> bool:
        """Call canExecute() view — returns (bool allowed, bytes reason)."""
        result = self.contract.functions.canExecute(req).call()
        return result[0]

    def can_execute_as(self, req: dict, agent: str) -> tuple:
        """Call canExecuteAs() for dry-run from an explicit agent address."""
        result = self.contract.functions.canExecuteAs(req, agent).call()
        return result[0], result[1]  # (allowed: bool, reason: bytes)

    def execute(self, req: dict, private_key: str) -> str:
        """Build, sign, and send an execute() transaction. Returns the tx hash hex string."""
        acct = self.w3.eth.account.from_key(private_key)
        nonce = self.w3.eth.get_transaction_count(acct.address)

        # Use EIP-1559 gas pricing on Arbitrum (avoids deprecated gasPrice)
        base_fee = self.w3.eth.get_block("latest").get("baseFeePerGas", 0)
        max_priority_fee = Web3.to_wei(0.1, "gwei")  # 0.1 gwei tip on Arbitrum
        max_fee = base_fee * 2 + max_priority_fee

        tx = self.contract.functions.execute(req).build_transaction({
            "from": acct.address,
            "nonce": nonce,
            "gas": 500_000,
            "maxFeePerGas": max_fee,
            "maxPriorityFeePerGas": max_priority_fee,
            "type": 2,  # EIP-1559
        })
        signed = acct.sign_transaction(tx)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        return tx_hash.hex()

    def is_paused(self) -> bool:
        return self.contract.functions.paused().call()


class RWAStateOracle(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "RWAStateOracle", w3)

    def is_eligible(self, asset: str, action: int) -> bool:
        return self.contract.functions.isEligible(asset, action).call()

    def get_asset_state(self, asset: str) -> dict:
        """Returns AssetState struct as a dict."""
        result = self.contract.functions.getAssetState(asset).call()
        return {
            "nav": result[0],
            "navUpdatedAt": result[1],
            "redemptionOpen": result[2],
            "liquidityTier": result[3],
            "supported": result[4],
            "maxNavAge": result[5],
        }

    def is_nav_fresh(self, asset: str) -> bool:
        return self.contract.functions.isNavFresh(asset).call()

    def is_approved_provider(self, provider: str) -> bool:
        return self.contract.functions.isApprovedProvider(provider).call()


class TBillVault(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "TBillVault", w3)

    def total_assets(self) -> int:
        return self.contract.functions.totalAssets().call()

    def total_supply(self) -> int:
        return self.contract.functions.totalSupply().call()

    def balance_of(self, address: str) -> int:
        return self.contract.functions.balanceOf(Web3.to_checksum_address(address)).call()


class AgentMandateRegistry(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "AgentMandateRegistry", w3)

    def validate_mandate(
        self,
        mandate_id: str,
        agent: str,
        target: str,
        action: int,
        amount: int,
    ) -> None:
        """Call the view validateMandate(). Raises if invalid."""
        self.contract.functions.validateMandate(
            mandate_id, agent, target, action, amount
        ).call()

    def get_mandate(self, mandate_id: str) -> dict:
        """Fetch the full Mandate struct."""
        result = self.contract.functions.getMandate(mandate_id).call()
        return {
            "agent": result[0],
            "asset": result[1],
            "allowedTarget": result[2],
            "allowedActionsMask": result[3],
            "maxTx": result[4],
            "maxCumulative": result[5],
            "used": result[6],
            "validFrom": result[7],
            "validUntil": result[8],
            "nonce": result[9],
            "revoked": result[10],
        }

    def mandate_owner(self, mandate_id: str) -> str:
        return self.contract.functions.mandateOwner(mandate_id).call()


class ComplianceRegistry(BaseContract):
    def __init__(self, address: str, w3: Web3):
        super().__init__(address, "ComplianceRegistry", w3)

    def is_kyc_approved(self, wallet: str) -> bool:
        return self.contract.functions.isKYCApproved(
            Web3.to_checksum_address(wallet)
        ).call()

    def is_sanctioned(self, wallet: str) -> bool:
        return self.contract.functions.isSanctioned(
            Web3.to_checksum_address(wallet)
        ).call()

    def is_wallet_eligible(self, wallet: str, asset: str, action: int) -> tuple:
        """Returns (eligible: bool, reason: bytes)."""
        return self.contract.functions.isWalletEligible(
            Web3.to_checksum_address(wallet),
            Web3.to_checksum_address(asset),
            action,
        ).call()


# ─────────────────────────────────────────────────────────────────────────────
# Web3 factory
# ─────────────────────────────────────────────────────────────────────────────

def build_web3(rpc_url: str) -> Web3:
    """Create a Web3 instance. Applies PoA middleware if available (Arbitrum Sepolia)."""
    w3 = Web3(Web3.HTTPProvider(rpc_url, request_kwargs={"timeout": 30}))
    if HAS_POA_MW:
        try:
            w3.middleware_onion.inject(_poa_mw, layer=0)
        except Exception:
            pass  # web3.py v7+ auto-handles PoA
    return w3
